### ISSUE TITLE
IndeedResult.total makes problems in Ruby 2.2.6

### ISSUE THREAD

**Issue by yegor256** [railsware/indeed#4] opened 2014-03-15 20:51 UTC
In Ruby 2.2.6 `IndeedResult` is not iterable (I don't know why). It gives all kinds of errors when I'm trying to `each` through its elements. Removing this line from `indeed.rb`:

```
self.total = total
```

fixes everything. Are you sure we need to store this `total` in the object? Renaming it to `totalResults` also fixes the problem. Looks like it conflicts with `Array` in Ruby. With 2.1.0 everything works fine with this `total` property.

**Comment by le0pard** [comment] 2014-03-15 22:04
> In Ruby 2.2.6 IndeedResult is not iterable (I don't know why)

Wow. I think it is because it is too new. I only have 2.1.1. If this is 2.1.1, in this case maybe influence regression in it - https://www.ruby-lang.org/en/news/2014/03/10/regression-of-hash-reject-in-ruby-2-1-1/

**Comment by yegor256** [comment] 2014-03-15 22:09
Would be great if we can rename `total` to `totalResults`. This problem blocks my project...

**Comment by le0pard** [comment] 2014-03-15 22:10
@yegor256 - just do pull request with tests. This must help for all.

**Comment by yegor256** [comment] 2014-03-15 22:17
#5 submitted

**Comment by le0pard** [comment] 2014-03-15 22:18
Merged

**Closed as completed** 2014-03-15 22:18 UTC
